config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'home#index'
  get 'timeline', to: 'articles#timeline'

  resources :articles, only: %i[new show create edit update]
  resources :users, only: %i[show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  attr_accessor :text_tags

  after_save :create_tags

  belongs_to :user

  has_many :article_goods, dependent: :destroy
  has_many :article_stocks, dependent: :destroy
  has_many :article_comments, dependent: :destroy
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags

  scope :unprivate, -> { where(private: false).order(created_at: :desc) }

  # status (
  # draft: 下書き,
  # active: アクティブ,
  # inactive: 非アクティブ(削除)
  # )
  enum status: { draft: 0, active: 10, inactive: 20 }

  with_options unless: :draft? do |undraft|
    undraft.validates :title, presence: true
    undraft.validates :content, presence: true
    undraft.validate :validate_article_tags_count
  end
  validates :status, presence: true, inclusion: { in: statuses.keys }

  def create_tags
    raise InvalidValueError, 'Article must have between 1 and 5 tags' if tags.empty? && !valid_tags_count?

    return if text_tags.nil?

    article_tags.destroy_all
    text_tags.split.map do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name)
      ArticleTag.find_or_create_by(article: self, tag:)
    end
  end

  private

  def validate_article_tags_count
    errors.add(:base, 'Article must have between 1 and 5 tags') unless valid_tags_count?
  end

  def valid_tags_count?
    tags_count = text_tags&.split&.uniq&.size
    (1..5).cover?(tags_count)
  end
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  has_many :article_comment_goods, dependent: :destroy

  validates :content, presence: true
end

app/models/article_comment_good.rb
class ArticleCommentGood < ApplicationRecord
  belongs_to :user
  belongs_to :article_comment

  counter_culture :article_comment, column_name: proc { |model| model.active? ? 'goods_count' : nil }

  # status (
  # active: アクティブ,
  # inactive：非アクティブ
  # )
  enum status: { active: 0, inactive: 10 }

  validates :status, presence: true, inclusion: { in: statuses.keys }
  validates :user_id, presence: true
  validates :article_comment_id, presence: true
  validates_uniqueness_of :user_id, scope: :article_comment_id
end

app/models/article_good.rb
class ArticleGood < ApplicationRecord
  belongs_to :user
  belongs_to :article

  counter_culture :article, column_name: proc { |model| model.active? ? 'goods_count' : nil }

  # status (
  # active: アクティブ,
  # inactive：非アクティブ
  # )
  enum status: { active: 0, inactive: 10 }

  validates :status, presence: true, inclusion: { in: statuses.keys }
  validates :user_id, presence: true
  validates :article_id, presence: true
  validates_uniqueness_of :user_id, scope: :article_id
end

app/models/article_stock.rb
class ArticleStock < ApplicationRecord
  belongs_to :user
  belongs_to :article

  counter_culture :article, column_name: proc { |model| model.active? ? 'stocks_count' : nil }

  # status (
  # active: アクティブ,
  # inactive：非アクティブ
  # )
  enum status: { active: 0, inactive: 10 }

  validates :status, presence: true, inclusion: { in: statuses.keys }
  validates :user_id, presence: true
  validates :article_id, presence: true
  validates_uniqueness_of :user_id, scope: :article_id
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag

  validates :article_id, presence: true
  validates :tag_id, presence: true
  validates_uniqueness_of :article_id, scope: :tag_id
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :name, presence: true
end

app/models/organization_fellowship.rb
class OrganizationFellowship < ApplicationRecord
  belongs_to :user
  belongs_to :organization

  counter_culture :organization, column_name: 'followers_count'

  validates :user_id, presence: true
  validates :organization_id, presence: true
  validates_uniqueness_of :user_id, scope: :organization_id
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/question_comment.rb
class QuestionComment < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :content, presence: true
end

app/models/question_comment_good.rb
class QuestionCommentGood < ApplicationRecord
  belongs_to :user
  belongs_to :question_comment

  counter_culture :question_comment, column_name: proc { |model| model.active? ? 'goods_count' : nil }

  # status (
  # active: アクティブ,
  # inactive：非アクティブ
  # )
  enum status: { active: 0, inactive: 10 }

  validates :status, presence: true, inclusion: { in: statuses.keys }
  validates :user_id, presence: true
  validates :question_comment_id, presence: true
  validates_uniqueness_of :user_id, scope: :question_comment_id
end

app/models/question_good.rb
class QuestionGood < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :article_goods
  has_many :article_comments
  has_many :article_comment_goods
  has_many :questions
  has_many :question_goods
  has_many :question_comments
  has_many :question_comment_goods
  has_many :question_comment_threads
  has_many :question_comment_thread_goods
  has_many :tags, through: :articles

  has_one_attached :image

  before_create :set_default_image

  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
  with_options if: :initial_setting? do |init|
    init.validates :name, presence: true
    init.validates :nickname, presence: true
    init.validates :image, presence: true
  end

  private

  def set_default_image
    return if image.attached?

    image_path = Rails.root.join('app', 'assets', 'images', 'user_default_image.png')
    image.attach(io: File.open(image_path), filename: 'user_default_image.png', content_type: 'image/png')
  end
end

app/models/user_fellowship.rb
class UserFellowship < ApplicationRecord
  belongs_to :follower, class_name: 'User', foreign_key: :follower_id
  belongs_to :followee, class_name: 'User', foreign_key: :followee_id
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    status = params[:publish_button].present? ? 'active' : 'inactive'
    @article = Article.new(article_create_params.merge(status:))

    ActiveRecord::Base.transaction do
      if @article.save
        redirect_to @article
      else
        render :new
      end
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = ArticleComment.new
  end

  def edit
    @article = Article.find(params[:id])
    tag_names = @article.tags.map(&:name)
    @article.text_tags = tag_names.join(' ')
  end

  def update
    @article = Article.find(params[:id])
    status = params[:publish_button].present? ? 'active' : 'inactive'

    ActiveRecord::Base.transaction do
      if @article.update(article_create_params.merge(status:))
        redirect_to @article
      else
        render :new
      end
    end
  end

  def timeline; end

  private

  def article_create_params
    params.require(:article).permit(:title, :content, :text_tags).merge(user: current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  PAGE_SIZE = 10

  def index
    @articles = Article.order('RANDOM()').limit(PAGE_SIZE)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_update_params)
      flash[:notice] = 'プロフィールが変更されました'
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_update_params
    params.require(:user).permit(:name, :nickname, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div>
    <p>エラーが発生しました:</p>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="h-full">
  <%= form.text_field :title,
                      placeholder: '記事タイトル',
                      class: 'rounded border-none py-1 mb-2 w-full outline-none focus:outline-none focus:border-none font-bold text-2xl' %>
  <%= form.text_field :text_tags,
                      placeholder: 'タグを入力してください。スペース区切りで5つまで入力できます.',
                      class: 'rounded border-none py-1 mb-2 w-full focus:outline-none' %>
  <%= form.text_area :content,
                     placeholder: '本文',
                     class: 'rounded border-custom-gray py-1 mb-2 w-full h-full focus:outline-none focus:border-none' %>
</div>
<div class="">
  <%= form.submit '下書き保存', name: 'draft_button', class: 'font-bold bg-white p-2 rounded-lg mr-2 cursor-pointer' %>
  <%= form.submit '公開設定', name: 'publish_button', class: 'font-bold text-white bg-custom-green border border-green-500 p-2 rounded-lg cursor-pointer' %>
</div>

app/views/articles/edit.html.erb
<div class="p-2 h-screen-minus-header flex flex-col">
  <%= form_with(model: @article, url: article_path(@article), method: :put, data: { turbo: false }, html: { class: 'h-full' }) do |form| %>
    <%= render partial: 'form', locals: { form: } %>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="p-2 h-screen-minus-header flex flex-col">
  <%= form_with(model: @article, url: articles_path(@article), method: :post, data: { turbo: false }, html: { class: 'h-full' }) do |form| %>
    <%= render partial: 'form', locals: { form: } %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="py-10 px-6">
  <div class="flex">
    <div class="mr-6">
      <%= link_to root_path, class: 'block text-center' do %>
        <div class="bg-white rounded-full border p-2">
          <%= render 'atoms/good', size: 6 %>
        </div>
      <% end %>
      <%= link_to root_path, class: 'block mx-auto mb-4 text-center' do %>
        <span class="text-sm font-bold hover:underline"><%= @article.goods_count %></span>
      <% end %>
      <%= link_to root_path, class: 'block mb-4 text-center' do %>
        <div class="bg-white rounded-full border p-2">
          <%= render 'atoms/stock', size: 6 %>
        </div>
        <span class="text-sm font-bold"><%= @article.stocks_count %></span>
      <% end %>
      <div class='block mb-4 text-center' data-controller="modal">
        <div class="p-2 relative">
          <span class="font-bold text-gray-500 cursor-pointer" data-action="click->modal#toggleModal">...</span>
          <div class="absolute top-[-100px] left-8 bg-white border-2 w-60 rounded-lg hidden" data-modal-target="modal">
            <div class="px-4 pb-4 border-b">
              <span class="text-gray-500 text-sm text-start font-bold mb-2">記事の改善</span>
              <%= link_to '編集リクエストを送る', root_path, class: 'block hover:bg-custom-gray' %>
            </div>
            <div class="p-4 border-b">
              <span class="text-gray-500 text-sm font-bold mb-2">記事の情報</span>
              <%= link_to '編集履歴', root_path, class: 'block mb-2 hover:bg-custom-gray' %>
              <%= link_to '編集リクエスト一覧', root_path, class: 'block mb-2 hover:bg-custom-gray' %>
              <%= link_to 'いいねしたユーザー一覧', root_path, class: 'block mb-2 hover:bg-custom-gray' %>
              <%= link_to 'Markdown で本文を見る', root_path, class: 'block hover:bg-custom-gray' %>
            </div>
            <div class="p-4 border-b">
              <%= link_to '記事を購読する', root_path, class: 'block mb-2 hover:bg-custom-gray' %>
              <%= link_to '問題がある記事を報告する', root_path, class: 'block hover:bg-custom-gray' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="w-full">
      <div class="bg-white py-8 px-12 mb-6 rounded-lg">
        <% if @article.private? %>
          <div class="bg-blue-100 py-6 px-4">
            <p class="text-custom-blue">
              この記事は限定共有記事です。投稿者本人とURLを知っているユーザーのみがアクセスできます。
              記事を全体公開するには、公開設定で公開範囲を「全体に公開」にしてください。
            </p>
          </div>
        <% end %>
        <div class="flex">
          <div class="w-6 h-6 rounded-full overflow-hidden mr-2">
            <%= image_tag @article.user.image, class: 'w-full h-full object-cover' %>
          </div>
          <div class="flex flex-col">
            <span class="block font-semibold">@<%= @article.user.name %>(<%= @article.user.nickname %>)</span>
          </div>
        </div>
        <div class="mb-4">
          <h2 class="text-2xl font-bold"><%= @article.title %></h2>
        </div>
        <div class="mb-4">
          <% @article.tags.each do |tag| %>
            <span class="bg-custom-gray rounded text-sm inline-block px-2 mx-0.5"><%= tag.name %></span>
          <% end %>
        </div>
        <div class="text-gray-500 text-sm mb-20">
          <% if @article.updated_at > @article.created_at %>
            <span class="mr-2">最終更新日 <%= l @article.updated_at %></span>
          <% end %>
          <span>投稿日 <%= l @article.created_at %></span>
          <%# TODO: 閲覧履歴 %>
          <% if user_signed_in? && @article.user.id == current_user.id %>
            <span>◯◯ views</span>
          <% end %>
        </div>
        <div class="pb-20">
          <p class="">
            <%= @article.content %>
          </p>
        </div>
      </div>
      <div class="bg-white py-8 px-12 mb-6 rounded-lg">
        <div class="flex">
          <div class="w-16 h-16 rounded-full overflow-hidden mr-2">
            <%= image_tag @article.user.image, class: 'w-full h-full object-cover' %>
          </div>
          <div class="flex flex-col justify-between">
            <span class="block font-semibold">@<%= @article.user.name %>(<%= @article.user.nickname %>)</span>
            <span class="block"><%= @article.user.profile %></span>
          </div>
        </div>
      </div>
      <% if user_signed_in? && @article.user.id == current_user.id %>
        <%= link_to '編集', edit_article_path(@article), class: 'border-2 border-custom-green rounded-full' %>
      <% end %>
      <div class="bg-white py-6 mb-6 rounded-lg">
        <h3 class="px-12 border-b mb-6 font-bold">コメント</h3>
        <% if user_signed_in? %>
          <div class="px-12">
            <div class="flex items-center mb-4">
              <div class="w-10 h-10 rounded-full overflow-hidden mr-2">
                <%= image_tag current_user.image, class: 'w-full h-full object-cover' %>
              </div>
              <span>コメントする</span>
            </div>
            <%= form_with(model: @comment, url: articles_path(@comment), method: :post, data: { turbo: false }, html: { class: 'h-full' }) do |form| %>
              <%= form.text_area :content,
                                 placeholder: 'テキストを入力',
                                 class: 'rounded border py-1 mb-2 w-full focus:outline-none' %>
              <%= form.submit '投稿する', class: 'font-bold text-white bg-custom-green border border-green-500 p-2 rounded-lg cursor-pointer' %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>